/** Company facts from http://fengchengcar.en.alibaba.com */
export const company = {
  legalName: 'Changzhou Fengcheng Import And Export Co., Ltd.',
  legalNameZh: '常州丰成进出口有限公司',
  brandName: 'Fengcheng Auto Parts',
  brandShort: 'Fengcheng',
  tagline: 'Custom auto body parts & modified lights for global B2B buyers',
  alibabaStoreUrl: 'http://fengchengcar.en.alibaba.com',
  location: 'Danyang, Jiangsu Province, China',
  businessType: 'Custom Manufacturer',
  yearEstablished: 2025,
  employees: '101-200',
  floorspace: '23,575㎡',
  productionMachines: 31,
  annualOutput: '180,000 units',
  rdEngineers: 5,
  newProductsPerYear: 300,
  storeRating: '4.8/5',
  onTimeDelivery: '92.9%',
  responseTime: '≤4h',
  mainMarkets: 'North America (40%), Western Europe (30%), Mid East (20%)',
  mainCategories: 'Car Bumper, Car Body Kit, Car Hoods, Car Grille, Modified Lights',
  certifications: ['IATF16949', 'ISO9001', 'CCC', 'E-MARK', 'EEC'] as const,
  factoryImages: [
    'https://s.alicdn.com/@sc02/kf/H427e3a68113045bab6e01cd1ba618f59e.jpg_960x960.jpg',
    'https://s.alicdn.com/@sc02/kf/H8f7b609114214666be07c90bc8aa0b19A.jpg_960x960.jpg',
    'https://s.alicdn.com/@sc02/kf/H8ae0d36f5cfd47169f967e8a2f6c20a5i.jpg_960x960.jpg',
    'https://s.alicdn.com/@sc02/kf/H4f9d31d5a6714876bac49cecc8ba291dY.jpg_960x960.jpg',
    'https://s.alicdn.com/@sc02/kf/H7952badc38de4a4a9c017e8404e5dd573.jpg_960x960.jpg',
    'https://s.alicdn.com/@sc02/kf/H57c6899e174d4fc19802188784d9a754O.jpg_960x960.jpg',
  ],
  aboutEn: `Changzhou Fengcheng Import and Export Co., Ltd. is a custom manufacturer of aftermarket auto body parts and modified lighting. Our product range covers bumpers, body kits, hoods, grilles, fenders, doors, tailgates, headlights, and tail lights for major vehicle brands including Toyota, Jeep, Hyundai, Nissan, Isuzu, Mercedes-Benz, and more.

We support OEM, ODM, and agency cooperation, with minor customization, drawing-based customization, finished product inspection, and raw material traceability. Our Alibaba store rating is 4.8/5 with 92.9% on-time delivery.`,
  phone: process.env.NEXT_PUBLIC_COMPANY_PHONE || '',
  contactEmail: process.env.INQUIRY_TO_EMAIL || 'Contact via inquiry form',
  whatsappDefault: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || '',
} as const
