services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: lumadrive
      POSTGRES_PASSWORD: lumadrive
      POSTGRES_DB: lumadrive
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
