services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: fengcheng
      POSTGRES_PASSWORD: fengcheng
      POSTGRES_DB: fengcheng
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
